# Generated by Django 3.0.1 on 2020-01-07 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20191223_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="O número de telefone deve ser digitado no formato: '+258849293949'. São permitidos até 13 dígitos.", regex='^\\+?258?\\d{9,13}$')]),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
