# Generated by Django 3.0.1 on 2020-01-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200107_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='número_de_telefone',
        ),
    ]
